version: 2
updates:
    - package-ecosystem: npm
      directory: /
      schedule:
          interval: weekly
      open-pull-requests-limit: 5
      versioning-strategy: increase
      groups:
          dependencies:
              applies-to: version-updates
              dependency-type: all
              update-types:
                  - minor
                  - patch
              exclude-patterns:
                  - '@dhis2'
