version: 2
updates:
    - package-ecosystem: 'npm'
      directory: '/'
      schedule:
        interval: 'weekly'
      open-pull-requests-limit: 5
      versioning-strategy: 'increase'
      groups:
        dev-dependencies:
          applies-to: version-updates
          dependency-type: "development"
          update-types:
            - "minor"
            - "patch"
          exclude-patterns:
            - "@dhis2"

