export const ACCESSORY_PANEL_TAB_INPUT = 'INPUT'
export const ACCESSORY_PANEL_TAB_PROGRAM = 'PROGRAM'
export const ACCESSORY_PANEL_TAB_YOUR = 'YOUR'
export const ACCESSORY_PANEL_TAB_TRACKED_ENTITY = 'TRACKED_ENTITY'
export const ACCESSORY_PANEL_TAB_PROGRAMS_USING_TYPE = 'PROGRAMS_USING_TYPE'
export const ACCESSORY_PANEL_TAB_MAIN_DIMENSIONS = 'MAIN_DIMENSIONS'
export const ACCESSORY_PANEL_TAB_PROGRAM_DIMENSIONS = 'PROGRAM_DIMENSIONS'
export const ACCESSORY_PANEL_TAB_ENROLLMENT = 'ENROLLMENT'
export const ACCESSORY_PANEL_TAB_PROGRAM_INDICATORS = 'PROGRAM_INDICATORS'
export const ACCESSORY_PANEL_TAB_EVENT = 'EVENT'

// Data type grouping constants
export const ACCESSORY_PANEL_TAB_ORG_UNITS = 'ORG_UNITS'
export const ACCESSORY_PANEL_TAB_PERIODS = 'PERIODS'
export const ACCESSORY_PANEL_TAB_STATUSES = 'STATUSES'
export const ACCESSORY_PANEL_TAB_DATA = 'DATA'

// Helper function to generate unique card IDs for each stage
export const getStageCardId = (stageId) => `STAGE_${stageId}`
export const ACCESSORY_PANEL_DEFAULT_WIDTH = 260
export const ACCESSORY_PANEL_MIN_WIDTH = 180
export const ACCESSORY_PANEL_MIN_PX_AT_END = 50
export const PRIMARY_PANEL_WIDTH = 260
export const ARROW_LEFT_KEY = 'ArrowLeft'
export const ARROW_RIGHT_KEY = 'ArrowRight'
