#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

yarn d2-app-scripts i18n extract && \
    git add i18n && \
    yarn d2-style check --staged && \
    yarn build:actions && git add .github/actions/supported-versions/dist/index.js
