name: 'dhis2: nightly'

on:
    schedule:
        - cron: '1 3,6,9,12,15,18,21,23 * * *'

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
              with:
                  ref: chore/upgrade-cypress-and-cli-utils-cypress
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn d2-app-scripts build

            - uses: actions/upload-artifact@v3
              with:
                  name: app-build
                  path: |
                      **/build
                      !**/node_modules
                  retention-days: 1

    e2e-v38:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: chore/upgrade-cypress-and-cli-utils-cypress

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: End-to-End tests
              uses: cypress-io/github-action@v5
              with:
                  start: yarn d2-app-scripts start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  record: true
                  parallel: true
                  browser: chrome
              env:
                  BROWSER: none
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  CYPRESS_dhis2BaseUrl: https://test.e2e.dhis2.org/analytics-2.38
                  CYPRESS_dhis2ApiVersion: 38
                  CYPRESS_dhis2InstanceVersion: 38
                  CYPRESS_networkMode: live
                  CYPRESS_dhis2Username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
                  CYPRESS_dhis2Password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}
                  DEBUG: 'cypress:*'

    e2e-v39:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: chore/upgrade-cypress-and-cli-utils-cypress

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: End-to-End tests
              uses: cypress-io/github-action@v5
              with:
                  start: yarn d2-app-scripts start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  record: true
                  parallel: true
                  browser: chrome
              env:
                  BROWSER: none
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  CYPRESS_dhis2BaseUrl: https://test.e2e.dhis2.org/analytics-2.39
                  CYPRESS_dhis2ApiVersion: 39
                  CYPRESS_dhis2InstanceVersion: 39
                  CYPRESS_networkMode: live
                  CYPRESS_dhis2Username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
                  CYPRESS_dhis2Password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}
                  DEBUG: 'cypress:*'
    e2e-v40:
        runs-on: ubuntu-latest

        strategy:
            fail-fast: false

        steps:
            - name: Checkout
              uses: actions/checkout@v3
              with:
                  ref: chore/upgrade-cypress-and-cli-utils-cypress

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: End-to-End tests
              uses: cypress-io/github-action@v5
              with:
                  start: yarn d2-app-scripts start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  record: true
                  parallel: true
                  browser: chrome
              env:
                  BROWSER: none
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  CYPRESS_dhis2BaseUrl: https://test.e2e.dhis2.org/analytics-2.40
                  CYPRESS_dhis2ApiVersion: 40
                  CYPRESS_dhis2InstanceVersion: 40
                  CYPRESS_networkMode: live
                  CYPRESS_dhis2Username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
                  CYPRESS_dhis2Password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}
                  DEBUG: 'cypress:*'
