name: 'dhis2: verify (commits)'

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

jobs:
    reusable_verify_commit_workflow_job:
        uses: dhis2/workflow-app-verify-commits/.github/workflows/dhis2-verify-commits.yml@v1
