name: 'dhis2: verify (app)'

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']
    push:
        branches:
            - 'master'
            - 'dev'

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    GH_TOKEN: ${{secrets.DHIS2_BOT_GITHUB_TOKEN}}
    D2_VERBOSE: true
    CI: true

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Build
              run: yarn d2-app-scripts build

            - uses: actions/upload-artifact@v3
              with:
                  name: app-build
                  path: |
                      **/build
                      !**/node_modules
                  retention-days: 1

    lint:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Generate translations
              run: yarn d2-app-scripts i18n generate

            - name: Lint
              run: yarn d2-style check

    test:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Test
              run: yarn d2-app-scripts test

    e2e-v38:
        runs-on: ubuntu-latest
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"

        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2, 3, 4]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: End-to-End tests
              uses: cypress-io/github-action@v5
              with:
                  start: yarn d2-app-scripts start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  record: true
                  parallel: true
                  browser: chrome
              env:
                  BROWSER: none
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  CYPRESS_dhis2BaseUrl: https://test.e2e.dhis2.org/analytics-2.38
                  CYPRESS_dhis2ApiVersion: 38
                  CYPRESS_dhis2InstanceVersion: 38
                  CYPRESS_networkMode: live
                  CYPRESS_dhis2Username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
                  CYPRESS_dhis2Password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}

    e2e-v39:
        runs-on: ubuntu-latest
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"

        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2, 3, 4]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: End-to-End tests
              uses: cypress-io/github-action@v5
              with:
                  start: yarn d2-app-scripts start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  record: true
                  parallel: true
                  browser: chrome
              env:
                  BROWSER: none
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  CYPRESS_dhis2BaseUrl: https://test.e2e.dhis2.org/analytics-2.39
                  CYPRESS_dhis2ApiVersion: 39
                  CYPRESS_dhis2InstanceVersion: 39
                  CYPRESS_networkMode: live
                  CYPRESS_dhis2Username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
                  CYPRESS_dhis2Password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}
    e2e-v40:
        runs-on: ubuntu-latest
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"

        strategy:
            fail-fast: false
            matrix:
                containers: [1, 2, 3, 4]

        steps:
            - name: Checkout
              uses: actions/checkout@v3

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - name: End-to-End tests
              uses: cypress-io/github-action@v5
              with:
                  start: yarn d2-app-scripts start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  record: true
                  parallel: true
                  browser: chrome
              env:
                  BROWSER: none
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  CYPRESS_dhis2BaseUrl: https://test.e2e.dhis2.org/analytics-2.40
                  CYPRESS_dhis2ApiVersion: 40
                  CYPRESS_dhis2InstanceVersion: 40
                  CYPRESS_networkMode: live
                  CYPRESS_dhis2Username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
                  CYPRESS_dhis2Password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}

    release:
        runs-on: ubuntu-latest
        needs: [build, lint, test, e2e-v38, e2e-v39, e2e-v40]
        if: |
            !github.event.push.repository.fork &&
            github.actor != 'dependabot[bot]' &&
            github.ref == 'refs/heads/master'
        steps:
            - uses: actions/checkout@v3
              with:
                  token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

            - uses: actions/setup-node@v3
              with:
                  node-version: 16.x

            - uses: actions/download-artifact@v3
              with:
                  name: app-build

            - name: Install
              run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-apphub: true
                  publish-github: true
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
                  apphub-token: ${{ secrets.DHIS2_BOT_APPHUB_TOKEN }}

            - uses: dhis2/deploy-build@master
              with:
                  build-dir: build/app
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

    report-release-failure:
        runs-on: ubuntu-latest
        needs: release
        if: |
            failure() &&
            !cancelled() &&
            github.ref == 'refs/heads/master'
        steps:
            - name: Send failure message to analytics-internal-bot slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.23.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  slack-message: ':small_red_triangle_down: Line-listing-app release <https://github.com/dhis2/line-listing-app/actions/workflows/dhis2-verify-app.yml?query=branch%3Amaster+is%3Afailure>'
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
