name: 'dhis2: verify (app)'

on: push

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    D2_VERBOSE: true

jobs:
    call-workflow-build-lint-test:
        uses: ./.github/workflows/build-lint-test@dev

    release:
        runs-on: ubuntu-latest
        needs: [build, lint, test]
        if: "!github.event.push.repository.fork && github.actor != 'dependabot[bot]'"
        steps:
            - uses: actions/checkout@v2
              with:
                  token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - uses: actions/download-artifact@v2
              with:
                  name: app-build

            # ensure that d2-app-scripts is available
            - uses: c-hive/gha-yarn-cache@v1
            - run: yarn install --frozen-lockfile

            - uses: dhis2/action-semantic-release@master
              with:
                  publish-apphub: true
                  publish-github: true
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}
                  apphub-token: ${{ secrets.DHIS2_BOT_APPHUB_TOKEN }}

            - uses: dhis2/deploy-build@master
              with:
                  build-dir: build/app
                  github-token: ${{ secrets.DHIS2_BOT_GITHUB_TOKEN }}

    report-failure-to-slack:
        runs-on: ubuntu-latest
        needs: [call-workflow-build-lint-test, release]
        if: |
            always() &&
            github.ref == 'refs/heads/dev' &&
            contains(needs.*.result, 'failure')

        steps:
            - name: Send failure message to analytics-internal-bot slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.23.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  slack-message: ':small_circle: Line-listing-app build <dhis2/line-listing-app/actions/workflows/dhis2-verify-app.yml?query=branch%3Adev|failed>'
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
