name: 'e2e-custom'

on:
    issue_comment:
        types: [created]

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    call-workflow-e2e-dev:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v2

            - name: Check comment for keyword
              id: check_keyword
              run: |
                  COMMENT_BODY="${{ github.event.comment.body }}"
                  if [[ "$COMMENT_BODY" == *"your-keyword-here"* ]]; then
                    echo "::set-output name=keyword_found::true"
                  else
                    echo "::set-output name=keyword_found::false"
                  fi

            - name: React to keyword
              if: steps.check_keyword.outputs.keyword_found == 'true'
              run: |
                  echo "Keyword found"
