name: 'e2e-prod'

# Requirements:
#
# - Customize environment variables:
#     BASE_URL_INSTANCES: Set the base url for the instances, e.g. https://test.e2e.dhis2.org
#     NAME_PATTERN_PROD_INSTANCES: Set the name pattern for your instances. {version} will be replaced by "[majorVersion].[minorVersion]"
#     NAME_PATTERN_DEV_INSTANCE: Set the name pattern for your dev instance. {version} will be replaced by "dev"
#
# - Other optional customizations:
#     containers: Set the matrix containers array for the e2e-prod job. The number of parallel Cypress instances running for each backend version will equal the array length.
#
# - Set status check as required:
#     We recommend setting "e2e-tests-success"  as a required step in your workflow.

on:
    workflow_call:
        secrets:
            baseurl:
                required: true
            username:
                required: true
            password:
                required: true
            recordkey:
                required: true

env:
    BASE_URL_INSTANCES: https://test.e2e.dhis2.org
    NAME_PATTERN_PROD_INSTANCES: 'analytics-{version}'
    NAME_PATTERN_DEV_INSTANCE: analytics-dev
    DHIS2_INSTANCE: https://test.e2e.dhis2.org/analytics-2.40

concurrency:
    group: e2e-prod-${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    e2e-prod:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-node@v3
              with:
                  node-version: 18.x
            - uses: browser-actions/setup-chrome@v1
              with:
                  chrome-version: stable
            - run: |
                  echo "BROWSER_PATH=$(which chrome)" >> $GITHUB_ENV

            - name: Compute prod instance url
              id: instance-url
              run: |
                  url=${DHIS2_INSTANCE}
                  echo "url=$url" >> $GITHUB_OUTPUT
                  echo "url: $url"
              env:
                  version: 2.40

            - name: Run e2e tests
              uses: cypress-io/github-action@v5
              with:
                  start: yarn d2-app-scripts start
                  wait-on: 'http://localhost:3000'
                  wait-on-timeout: 300
                  browser: chrome
              env:
                  CI: true
                  BROWSER: none
                  CYPRESS_dhis2BaseUrl: ${{ steps.instance-url.outputs.url }}
                  CYPRESS_dhis2InstanceVersion: 2.40
                  CYPRESS_dhis2Username: ${{ secrets.username }}
                  CYPRESS_dhis2Password: ${{ secrets.password }}
                  CYPRESS_networkMode: live
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    e2e-tests-success:
        needs: e2e-prod
        if: ${{ success() || failure() }}
        runs-on: ubuntu-latest
        steps:
            - run: if [ $result != 'success' ]; then exit 1; fi;
              env:
                  result: ${{ needs.e2e-prod.result }}
