name: 'dhis2: e2e tests'
on:
    pull_request:
        types: [labeled]

env:
    BASE_URL_INSTANCES: https://test.e2e.dhis2.org
    NAME_PATTERN_LEGACY_INSTANCES: '{version}lytics-dev'
    NAME_PATTERN_DEV_INSTANCE: dev
    CYPRESS_CONTAINERS: 8
    TRIGGER_LABELS: e2e-tests, testing

defaults:
    run:
        shell: bash

jobs:
    prerequisites:
        runs-on: ubuntu-latest
        outputs:
            json-labels: ${{ steps.json-labels.outputs.labels }}
            matrix-containers: ${{ steps.matrix-containers.outputs.containers }}
            versions: ${{ steps.legacy-versions.outputs.versions }}
        steps:
            - name: compute-json-labels
              id: json-labels
              run: |
                  arrLabels=(${TRIGGER_LABELS//,/ })
                  for item in ${arrLabels[@]}; do labels+=\"$item\",; done
                  echo "::set-output name=labels::[ ${labels%,} ]"
            - name: compute-matrix-containers
              id: matrix-containers
              if: contains(fromJson(steps.json-labels.outputs.labels), github.event.label.name)
              run: |
                  for (( cnt = 1; cnt <= $CYPRESS_CONTAINERS; cnt++)); do containers+=$cnt,; done
                  echo "::set-output name=containers::[ ${containers%,} ]"
            - if: contains(fromJson(steps.json-labels.outputs.labels), github.event.label.name)
              uses: actions/checkout@v2

            - name: compute-instance-url
              id: instance-url
              if: contains(fromJson(steps.json-labels.outputs.labels), github.event.label.name)
              run: echo "::set-output name=url::${BASE_URL_INSTANCES%/}/${NAME_PATTERN_DEV_INSTANCE/"{version}"/dev}"

            - id: legacy-versions
              if: contains(fromJson(steps.json-labels.outputs.labels), github.event.label.name)
              uses: dhis2/action-supported-legacy-versions@v1
              with:
                  instance-url-latest: ${{ steps.instance-url.outputs.url }} # can be removed if maxDHIS2Version has been specified
                  username: ${{ secrets.CYPRESS_DHIS2_USERNAME }} # can be removed if maxDHIS2Version has been specified
                  password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }} # can be removed if maxDHIS2Version has been specified

    cypress:
        needs: prerequisites
        if: contains(fromJson(needs.prerequisites.outputs.json-labels), github.event.label.name)
        runs-on: ubuntu-latest
        container: cypress/browsers:node14.7.0-chrome84
        strategy:
            fail-fast: false
            matrix:
                versions: ${{ fromJSON(needs.prerequisites.outputs.versions) }}
                containers: ${{ fromJSON(needs.prerequisites.outputs.matrix-containers) }}
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: 16.x

            - name: compute-instance-url
              id: instance-url
              run: echo "::set-output name=url::${BASE_URL_INSTANCES%/}/${NAME_PATTERN_LEGACY_INSTANCES/"{version}"/$version}"
              env:
                  version: ${{ matrix.versions }}

            - name: Cypress run
              uses: cypress-io/github-action@v2
              with:
                  record: true
                  parallel: true
                  group: e2e-chrome-parallel-${{ matrix.versions }}
                  browser: chrome
                  start: yarn d2-app-scripts start
                  wait-on: http://localhost:3000
                  wait-on-timeout: 300
              env:
                  CI: true
                  CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CYPRESS_dhis2BaseUrl: ${{ steps.instance-url.outputs.url }}
                  CYPRESS_dhis2InstanceVersion: ${{matrix.versions}}
                  CYPRESS_dhis2Username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
                  CYPRESS_dhis2Password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}
                  CYPRESS_networkMode: live

    call-e2e-tests-result:
        needs: cypress
        uses: ./.github/workflows/e2e-tests-result.yml
        with:
            result: true
