name: 'dhis2: nightly'

# Requirements:
#
# - Secrets:
#     GITHUB_TOKEN
#     CYPRESS_DHIS2_USERNAME
#     CYPRESS_DHIS2_PASSWORD
#     CYPRESS_RECORD_KEY
#
# This workflow runs the e2e tests on the default branch against dev at 6:20am M-F

on:
    # schedule:
    # - cron: '20 5 * * 1-5'
    workflow_dispatch:
    push:
    # FOR TESTING ONLY! Remove before merge!

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}
    cancel-in-progress: true

defaults:
    run:
        shell: bash

jobs:
    call-workflow-e2e-dev:
        uses: dhis2/workflows/.github/workflows/analytics-e2e-tests-dev.yml@master
        secrets:
            username: ${{ secrets.CYPRESS_DHIS2_USERNAME }}
            password: ${{ secrets.CYPRESS_DHIS2_PASSWORD }}
            recordkey: ${{ secrets.CYPRESS_RECORD_KEY }}

    # FOR TESTING ONLY! Uncomment before merge!
    # send-slack-message:
    #     runs-on: ubuntu-latest
    #     needs: call-workflow-e2e-dev
    #     if: |
    #         failure() &&
    #         !cancelled()

    #     steps:
    #         - name: Send failure message to analytics-internal-kfmt slack channel
    #           id: slack
    #           uses: slackapi/slack-github-action@v1.23.0
    #           with:
    #               channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
    #               slack-message: ':x: Line-listing-app e2e nightly build <https://cloud.cypress.io/projects/m5qvjx/runs?branches=[{"label":"master","suggested":false,"value":"master"}]|failed>'
    #           env:
    #               SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
