name: 'PR-verify-app'

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']

concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    D2_VERBOSE: true

jobs:
    call-workflow-build-lint-test:
        uses: ./.github/workflows/build-lint-test.yml

    call-workflow-e2e-tests:
        needs: [call-workflow-build-lint-test]
        uses: ./.github/workflows/e2e-tests.yml
