name: 'dhis2: verify (app)'

on:
    pull_request:
        types: ['opened', 'edited', 'reopened', 'synchronize']


concurrency:
    group: ${{ github.workflow}}-${{ github.ref }}

env:
    GIT_AUTHOR_NAME: '@dhis2-bot'
    GIT_AUTHOR_EMAIL: 'apps@dhis2.org'
    GIT_COMMITTER_NAME: '@dhis2-bot'
    GIT_COMMITTER_EMAIL: 'apps@dhis2.org'
    D2_VERBOSE: true

jobs:
    call-workflow-build-lint-test:
        uses: ./.github/workflows/build-lint-test.yml

    call-workflow-e2e-tests:
        needs: [call-workflow-build-lint-test]
        uses: ./.github/workflows/e2e-tests.yml

    report-failure-to-slack:
        runs-on: ubuntu-latest
        needs: [call-workflow-build-lint-test, call-workflow-e2e-tests]
        if: |
            always() &&
            github.ref == 'refs/heads/dev' &&
            contains(needs.*.result, 'failure')

        steps:
            - name: Send failure message to analytics-internal-bot slack channel
              id: slack
              uses: slackapi/slack-github-action@v1.23.0
              with:
                  channel-id: ${{ secrets.SLACK_CHANNEL_ID }}
                  slack-message: ':small_circle: Line-listing-app build <dhis2/line-listing-app/actions/workflows/dhis2-verify-app.yml?query=branch%3Adev|failed>'
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
